- name: Create condor config parent directories
  file: 
   path: "{{ item }}"
   recurse: yes
   state: directory
  with_items:
    - /etc/condor/condor.d
    - /etc/condor/ganglia.d

- name: Create /etc/condor/condor_config
  template:
    src: condor_config.j2
    dest: /etc/condor/condor_config
    mode: 0644

- name: Create /etc/condor/condor.d/00-htcondor-9.0.config
  template:
    src: 00-htcondor-9.0.config.j2
    dest: /etc/condor/condor.d/00-htcondor-9.0.config
    mode: 0644

- name: Create /etc/condor/ganglia.d/00_default_metrics
  template:
    src: 00_default_metrics.j2
    dest: /etc/condor/ganglia.d/00_default_metrics
    mode: 0644

- name: Create /etc/condor/condor_config.local
  template:
    src: condor_config.local.j2
    dest: /etc/condor/condor_config.local
    mode: 0644
  environment:
    CONDOR_CONFIG: /etc/condor/condor_config.local
  when:
    - CLOUD_SITE_ID is defined
    - HTCONDOR_CONFIG_GIT_REPO is defined

- name: Create link to condor_ssh_to_job_sshd_config_template
  ansible.builtin.file:
    src: /usr/lib64/condor/condor_ssh_to_job_sshd_config_template
    dest: /etc/condor/condor_ssh_to_job_sshd_config_template
    state: link
