- name: Add token password to directory
  block:
    - name: Add base64 encoded token passwords to directory
      shell: |
        echo '{{ item.value }}' | base64 --decode > {{ SEC_PASSWORD_DIRECTORY.stdout + item.key }} && chmod 0600 {{ SEC_PASSWORD_DIRECTORY.stdout + item.key }}
  rescue:
    - name: Add token passwords directly to directory
      copy:
        dest:  "{{ SEC_PASSWORD_DIRECTORY.stdout + item.key }}"
        content: "{{ item.value }}"
        mode: "0600"