- name: Get pool password file
  command: "condor_config_val SEC_PASSWORD_FILE"
  register: SEC_PASSWORD_FILE
  changed_when: SEC_PASSWORD_FILE.rc == 0

- name: Add directory for the pool password
  file:
    path: "{{ SEC_PASSWORD_FILE.stdout | dirname }}"
    recurse: yes
    state: directory
    mode: 0755

- name: Add HTCondor Pool Password
  block:
    - name: Add HTCondor Base64 encoded Pool Password
      shell: |
        echo '{{ HTCONDOR_POOL_PASSWORD }}' | base64 --decode > {{ SEC_PASSWORD_FILE.stdout }}
        chmod 0600 {{ SEC_PASSWORD_FILE.stdout }}
      # does not work in python2.7 on centos7
      #copy:
      #  dest: "{{ SEC_PASSWORD_FILE.stdout }}"
      #  content: "{{ HTCONDOR_POOL_PASSWORD | b64decode }}"
      #  mode: 0600
  rescue:
    - name: Add HTCondor Pool Password String
      copy:
        dest: "{{ SEC_PASSWORD_FILE.stdout }}"
        content: "{{ HTCONDOR_POOL_PASSWORD }}"
        mode: 0600

#- name: Add HTCondor Pool Password
#  vars:
#    ansible_python_interpreter: /usr/bin/python3
#  expect:
#    command: /bin/bash -c "condor_store_cred add -c -f {{ SEC_PASSWORD_FILE.stdout }}"
#    responses:
#      "Enter password:": "{{ HTCONDOR_POOL_PASSWORD }}"
