- name: Create condor execute directory
  file:
   path: /var/lib/condor/execute
   recurse: yes
   state: directory
   mode: "1777"

- name: Create spool directory
  file:
    path: /var/lib/condor/spool/local_univ_execute
    recurse: yes
    state: directory
    mode: 0755